version: "3.8"
services:
  mysql:
    container_name: saju_nodejs_mysql
    image: mysql:5.7.27
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=duswlsms98
      - MYSQL_ROOT_PASSWORD=duswlsms98
      - MYSQL_DATABASE=saju_db_dev
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    command: ["mysqld", "--characcd ter-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
